Update patch set 8
Patch Set 8:

> Patch Set 7:
> 
> > Patch Set 5:
> > 
> > > Patch Set 5:
> > > 
> > > > Patch Set 5:
> > > > 
> > > > > ../../third_party/angle/src/compiler/translator/Common.h:62:16: error: no matching conversion for functional-style cast from 'const std::__1::basic_string<char, std::__1::char_traits<char>, pool_allocator<char> >' to 'std::hash<basic_string<char, char_traits<char>, pool_allocator<char> > >'
> > > > 
> > > > :(
> > > > We can discuss later what's wrong here, I might figure it out before then.
> > > 
> > > Seems like now the Windows version cares about TString being hashed. Not sure why.
> > 
> > I'm not sure if that's the issue. For some reason MSVC and libc++ (clang's STL) seem to think `std::hash<T>(__s)` is a functional-style cast, while libstdc++ (gcc's STL) thinks it's a function call. I suspect that neither this nor `std::hash(__s)` is valid in this context but there's too much template magic going on for me to be sure why.
> > 
> > I'll spend a few minutes playing with this, maybe it can be massaged into a form all 3 compilers like.
> 
> I think the issue here is that std::hash is a structure, not a function.  You would hash an object by calling std::hash<T>()(object);

Yeah, that did appear to be the issue. It's not needed anymore, though, since you suggested to use namespace std {}, which fixes that issue.

Patch-set: 8
Reviewer: Kai Ninomiya <1172235@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Label: Commit-Queue=0