Add back sdk_version entry to build targets
ANGLE in android repo are failing to compile on
some lunch targets: e.g. mainline_modules*, with
sdk_version entry removed from build targets.

For instance, after removing sdk_version for
build target libEGL_angle, compilation failed with
this error message:

```
error: external/angle/Android.bp:8174:1: dependency
"libEGL_angle" of "ANGLE" missing variant:
  os:android,arch:arm64_armv8-a,sdk:sdk,link:shared
available variants:
  os:android,arch:arm64_armv8-a,link:shared
  os:android,arch:arm_armv8-a,link:shared
```

Add back sdk_version entry to the build targets.
END2END_TEST_TARGET needs to be disabled, because
with sdk_version entry added to END2END_TEST_TARGET,
the target failed to compile due to its' dependency
libgmock is missing the variant:

```
error: external/angle/Android.bp:699:1: dependency "libgmock"
of "libangle_end2end_tests__library" missing variant:
  os:android,arch:arm64_armv8-a,sdk:sdk,link:static
```

Bug: b/279980674
Change-Id: I96ea45b93519b84d72a70559d1ade9076ef9d955
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/5857112
Reviewed-by: Cody Northrop <cnorthrop@google.com>
Commit-Queue: Yuxin Hu <yuxinhu@google.com>