Revert "Fix support for GL_MAX_ATTRIBS attributes."
Breaks the AMD bot's OpenGL tests.

VertexAttributeTest.MaxAttribs/3:
shader compilation failed: Vertex shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

shader compilation failed: Fragment shader failed to compile with the following errors:
ERROR: error(#272) Implicit version number 110 not supported by GL3 forward compatible context
ERROR: error(#273) 1 compilation errors.  No code generated

BUG=angleproject:1045
BUG=500116

This reverts commit 3f3d75ea6c20826adb6240f1573fd7139939a986.

Change-Id: I8cdd024fcf49f1ade553dae2cdbe8b02d8fba364
Reviewed-on: https://chromium-review.googlesource.com/277673
Reviewed-by: Jamie Madill <jmadill@chromium.org>
Tested-by: Jamie Madill <jmadill@chromium.org>