Suppress warnings from macOS 27 logging macros
Suppress `-Wignored-attributes` triggered when compiling macOS-specific
logging and tracing code in `debug.cpp`.

In the macOS 27 SDK introduced with Xcode 27, Apple has applied an
`OS_LOG_UNINITIALIZED` macro inside their logging and signposting
headers (`os/log.h`, `os/signpost.h`, `os/trace_base.h`) which expands
to include `__attribute__((stack_protector_ignore))`.

Because of this, stack protection checks are skipped on local formatting
buffers generated by logging macros such as `os_log_with_type` and
`os_signpost_event_emit`. However, in Flutter (and likely other ANGLE
users), we compile the engine with `-fstack-protector-all`, which causes
the build to error out complaining that the `stack_protector_ignore`
attribute is being ignored:

    error: 'stack_protector_ignore' attribute ignored due to '-fstack-protector-all' option [-Werror,-Wignored-attributes]

This wraps these usages in ignore pragmas to avoid disabling it across
the board.

Bug: b/523963866
Change-Id: Iee87ccddb6dd469a230d7e39a957bb441c41e4a2
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/7930232
Reviewed-by: Geoff Lang <geofflang@chromium.org>
Reviewed-by: Charlie Lao <cclao@google.com>
Auto-Submit: Chris Bracken <cbracken@google.com>
Commit-Queue: Geoff Lang <geofflang@chromium.org>