Fix to build with VS2019
When building with VS2019 (using is_clang=false) multiples of the
following error are given:

    ../../src/common/mathutil.cpp(75): error C4244: '=':
    conversion from 'double' to 'float', possible loss of data

(This is due to pow(), when passed an int for the second param, widens
the first param to a double then returns a double).

Since the code was being changed the opportunity was taken to:

    - add missing unit tests for the two 999E5 conversions
    - optimise out the common pow() functions

The unit tests were written against the original implementation, then
the optimisations added and verified against the original results.

Bug: angleproject:5521, dawn:602
Change-Id: Ic9e5eaedbe3fc7ceeed697898823b76dffcd989a
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/2624888
Commit-Queue: Jamie Madill <jmadill@chromium.org>
Reviewed-by: Jamie Madill <jmadill@chromium.org>