M139: Revert "Metal: Wraparound int arithmetic for add, sub"
This reverts commit 2f6f0514563d81e439e04ba09eee9e8a1d6ca8d1.

Reason for revert: Leads to MSL compiler errors:

> error: non-const reference cannot bind to vector element

Bug: angleproject:382215759
Original change's description:
> Metal: Wraparound int arithmetic for add, sub
>
> Implement wraparound int arithmetic for
> int, ivec +, -, +=, -=, ++, --.
>
> All of the added tests pass also without the changes.
>
> Bug: angleproject:382215759
> Change-Id: I7605582ab2931e63010c34fba474797f7edd19f9
> Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6578729
> Auto-Submit: Kimmo Kinnunen <kkinnunen@apple.com>
> Reviewed-by: Shahbaz Youssefi <syoussefi@chromium.org>
> Reviewed-by: Geoff Lang <geofflang@chromium.org>
> Commit-Queue: Kimmo Kinnunen <kkinnunen@apple.com>

Bug: angleproject:382215759
Bug: chromium:425746892
Change-Id: Icba824743747ad84c39aa01b964b36a3a5b26a5d
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6655945
Reviewed-by: Solti Ho <solti@google.com>