Update patch set 17
Patch Set 17:

> Patch Set 17:
> 
> This patch doesn't work on VS2015 and I don't think it would be easy to make it work. Specifically, the rather complex constexpr function:
> constexpr const char *GetBasicMangledName(TBasicType t)
> doesn't work:
> "[switch] statement may not appear in a constexpr function"
> BaseTypes.h(134): error C3249: illegal statement or sub-expression for 'constexpr' function

I met similar issue in Linux for gyp build. When I use gyp build in Linux (Unbuntu 17.10), it has similar errors and fails to build ANGLE. But it is OK for gn build. Prior to this patch, both gyp build and gn build are OK. 

Now that Chromium and ANGLE are switching to gn, so I didn't explore the difference between gn build and gyp build in ANGLE for constexpr.

Patch-set: 17