Roll Chromium from 561dfad17c04 to 995d777c7731 (623 revisions)
https://chromium.googlesource.com/chromium/src.git/+log/561dfad17c04..995d777c7731

Disables global constructor/destructor warnings when using GlobalMutex,
which started triggering after this Clang roll here:
https://chromium-review.googlesource.com/c/chromium/src/+/6354907
src/libANGLE/GlobalMutex.cpp:124:24:
error: declaration requires a global constructor
  124 | void ANGLE_CONSTRUCTOR AllocateGlobalMutex()
src/libANGLE/GlobalMutex.cpp:132:23:
error: declaration requires a global destructor
  132 | void ANGLE_DESTRUCTOR DeallocateGlobalMutex()

If this roll has caused a breakage, revert this CL and stop the roller
using the controls here:
https://autoroll.skia.org/r/chromium-angle-autoroll
Please CC angle-team@google.com,syoussefi@google.com on the revert to
ensure that a human
is aware of the problem.

To file a bug in Chromium:
https://bugs.chromium.org/p/chromium/issues/entry
To file a bug in ANGLE:
https://bugs.chromium.org/p/angleproject/issues/entry

To report a problem with the AutoRoller itself, please file a bug:
https://issues.skia.org/issues/new?component=1389291&template=1850622

Documentation for the AutoRoller is here:
https://skia.googlesource.com/buildbot/+doc/main/autoroll/README.md

Changed dependencies
* build: https://chromium.googlesource.com/chromium/src/build.git/+log/aafbb3185f..1dc5fbff43
* buildtools: https://chromium.googlesource.com/chromium/src/buildtools.git/+log/8550f0913b..7f1053216c
* testing: https://chromium.googlesource.com/chromium/src/testing/+log/51cf51a3cd..35bdf40ed0
* third_party/android_build_tools/error_prone/cipd: PUFyo5eTRLBVraTti00zSIPJ9JJazDE9OU5e-mc6sicC..TKp0LDZjoG40SrElfQevGD9zDvVypBnRPWTzv8bnTw4C
* third_party/android_build_tools/lint/cipd: tsOuC8RTor7xvEQGKjf4UUWbOZ6CXLUAWTapMfyjtSIC..vhjMonh9XYLLHAk7HJJI88WCaEq0Wye3mcXRgZto0hgC
* third_party/android_build_tools/manifest_merger/cipd: XsYjBCg98jVV1y2tdwYTvXS_V_53hDdGBdsLsI_Cd-AC..pUhXoFF33hA0Ld7PAOJp2fl0HLa6foRELt7yy1i_L9oC
* third_party/catapult: https://chromium.googlesource.com/catapult.git/+log/4d2793429f..828df14a60
* third_party/fuchsia-sdk/sdk: version:27.20250308.2.1..version:27.20250315.3.1
* third_party/llvm-libc/src: https://chromium.googlesource.com/external/github.com/llvm/llvm-project/libc.git/+log/f752139824..14489e08b2
* third_party/protobuf: https://chromium.googlesource.com/chromium/src/third_party/protobuf/+log/38d40010d1..dbe04005a2
* third_party/r8/cipd: FiKym6sa--ha6Yuxe-KJYyUo-CPERJJ5FYurwPkrvyoC..OB23bnkEllPjA4Mmlh2kdHOMJGV19SMZobx2U4KGuPIC
* third_party/rust: https://chromium.googlesource.com/chromium/src/third_party/rust/+log/97cf54e65e..c980724668
* third_party/siso/cipd: git_revision:6b0b080aea4fa142b573795daa977e8751947452..git_revision:3a38836e06344016dce6092148a07a114807f9f0
* tools/clang: https://chromium.googlesource.com/chromium/src/tools/clang.git/+log/d4d0079e13..c82c0e7bb5
* tools/perf: https://chromium.googlesource.com/chromium/src/tools/perf/+log/168fff5a3e..b441f42f7e
* tools/rust: https://chromium.googlesource.com/chromium/src/tools/rust.git/+log/d4b64d95f4..f26c92c0db
Clang version changed llvmorg-21-init-1655-g7b473dfe:llvmorg-21-init-5118-g52cd27e6
Details: https://chromium.googlesource.com/chromium/src/tools/clang/+/d4d0079e135e52df927a2828f0085e4e90f0de2b..c82c0e7bb5b235463a52234216507466a49c1ba8/scripts/update.py

Bug: angleproject:42266550
Change-Id: I96c1952485944e119798eb0f3be4206c7ed321d6
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6360302
Reviewed-by: Shahbaz Youssefi <syoussefi@chromium.org>
Commit-Queue: Yuly Novikov <ynovikov@chromium.org>