Update patch set 33
Patch Set 33:

Thank you! Olli. 
I modified the code and I think I did the similar thing as in MipmapTest.cpp. But I still get some errors:

shader compilation failed: 
0(2): error C5060: out can't be used with non-varying fragColor
0(4): warning C7532: global type uint requires "#version 130" or later
0(4): warning C0000: ... or #extension GL_EXT_gpu_shader4: enable
0(4): warning C7532: global function packSnorm2x16 requires "#version 420" or later
0(4): warning C0000: ... or #extension GL_ARB_shading_language_packing: enable
0(5): warning C7532: global function unpackSnorm2x16  requires "#version 420" or later
0(5): warning C0000: ... or #extension GL_ARB_shading_language_packing: enable
0(2): error C5060: out can't be used with non-varying fragColor



I'm just confused. Would you please help me?
Thanks!

Patch-set: 33