Update patch set 1
Patch Set 1:

g++ -MMD -MF obj/libANGLE/ImageIndex.o.d -DANGLE_GENERATE_SHADER_DEBUG_INFO -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DCOMPONENT_BUILD -DCR_SYSROOT_HASH=4e7db513b0faeea8fb410f70c9909e8736f5c0ab -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_GLIBCXX_DEBUG=1 -DANGLE_ENABLE_DEBUG_ANNOTATIONS -DGL_GLEXT_PROTOTYPES -DEGL_EGLEXT_PROTOTYPES -DANGLE_IS_64_BIT_CPU -DANGLE_ENABLE_OPENGL -DANGLE_USE_X11 -DANGLE_ENABLE_OPENGL_NULL -DANGLE_ENABLE_VULKAN -DANGLE_ENABLE_NULL -DLIBANGLE_IMPLEMENTATION -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XCB_KHX -DANGLE_VK_DATA_DIR=\"angledata\" -DANGLE_VK_ICD_JSON=\"angledata/VkICD_mock_icd.json\" -DAPI_NAME=\"Vulkan\" -DHAVE_SECURE_GETENV -I../../src/third_party/khronos -Igen/angle -I../../include -I../../src -I../../src/common/third_party/base -I../../third_party/vulkan-validation-layers/src/include -I../../include -I../../src -I../../include -I../../src -I../../include -I../../third_party/glslang/src -I../../third_party/glslang/src/glslang/Public -Igen/third_party/vulkan-validation-layers/angle/vulkan -I../../third_party/vulkan-validation-layers/src/include -I../../third_party/vulkan-validation-layers/src/loader -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -pthread -m64 -march=x86-64 -Wall -Werror -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-deprecated-declarations -fno-delete-null-pointer-checks -Wno-comments -Wno-missing-field-initializers -Wno-unused-parameter -O0 -fno-omit-frame-pointer -g2 -gsplit-dwarf -fvisibility=hidden -std=gnu++14 -Wno-narrowing -fno-exceptions -fno-rtti --sysroot=../../build/linux/debian_sid_amd64-sysroot -fvisibility-inlines-hidden -c ../../src/libANGLE/ImageIndex.cpp -o obj/libANGLE/ImageIndex.o
In file included from ../../src/common/bitset_utils.h:18:0,
                 from ../../src/common/PackedEnums.h:21,
                 from ../../src/libANGLE/ImageIndex.h:12,
                 from ../../src/libANGLE/ImageIndex.cpp:9:
../../src/libANGLE/ImageIndex.cpp: In member function ‘bool gl::ImageIndex::has3DLayer() const’:
../../src/libANGLE/ImageIndex.cpp:86:34: error: suggest parentheses around comparison in operand of ‘==’ [-Werror=parentheses]
     ASSERT(!hasLayer() || (mType != TextureType::CubeMap == usesTex3D()));
                            ~~~~~~^~~~
../../src/common/debug.h:266:6: note: in definition of macro ‘ASSERT’
     (expression ? static_cast<void>(0) : ((ERR() << "\t! Assert failed in " << __FUNCTION__ << "(" \
      ^~~~~~~~~~
In file included from ../../src/common/debug.h:13:0,
                 from ../../src/common/bitset_utils.h:18,
                 from ../../src/common/PackedEnums.h:21,
                 from ../../src/libANGLE/ImageIndex.h:12,
                 from ../../src/libANGLE/ImageIndex.cpp:9:
../../src/libANGLE/ImageIndex.cpp:86:34: error: suggest parentheses around comparison in operand of ‘==’ [-Werror=parentheses]
     ASSERT(!hasLayer() || (mType != TextureType::CubeMap == usesTex3D()));
                            ~~~~~~^~~~
../../src/common/debug.h:268:43: note: in expansion of macro ‘ANGLE_ASSERT_IMPL’
                                           ANGLE_ASSERT_IMPL(expression)))
                                           ^~~~~~~~~~~~~~~~~
../../src/libANGLE/ImageIndex.cpp:86:5: note: in expansion of macro ‘ASSERT’
     ASSERT(!hasLayer() || (mType != TextureType::CubeMap == usesTex3D()));
     ^~~~~~
cc1plus: all warnings being treated as errors

Patch-set: 1
Reviewer: Jie A Chen <1109831@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>