Revert "Rename enums to fix GCC -Wchanges-meaning error"
This reverts commit dc24ecca9ed920c0269e9d62dfcac4b3f3e5a4d4.

Reason for revert: breaks ios-simulator build when rolled to Chromium
https://chromium-review.googlesource.com/c/chromium/src/+/6863632
https://ci.chromium.org/ui/p/chromium/builders/try/ios-simulator/2446924/overview
[10968/78005] OBJCXX obj/third_party/angle/util/angle_util_static/IOSWindow.o
sdk/xcode_links/iPhoneSimulator18.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSDictionary.h:17:38: error: reference to 'KeyType' is ambiguous
   17 | - (nullable ObjectType)objectForKey:(KeyType)aKey;

BUG: angleproject:438226513
Original change's description:
> Rename enums to fix GCC -Wchanges-meaning error
>
> Renamed enums Key and MouseButton to enum class KeyType and
> MouseButtonType to avoid name conflicts with union members in
> Event.h on GCC, and to follow the ANGLE style guide preference
> for scoped enums.
>
> BUG: angleproject:438226513
> Change-Id: I8892b438b3b05a3ce4e14f8c0769b81722688da8
> Signed-off-by: Sungyong Choi <sywow.choi@samsung.com>
> Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6845484
> Commit-Queue: Geoff Lang <geofflang@chromium.org>
> Reviewed-by: Shahbaz Youssefi <syoussefi@chromium.org>
> Reviewed-by: Geoff Lang <geofflang@chromium.org>

Bug: angleproject:438226513
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Change-Id: Iff0d925b9fa608215cff0e472074a0315f14e861
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6863019
Auto-Submit: Yuly Novikov <ynovikov@chromium.org>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>