Update patch set 1
Patch Set 1:

It's not extraordinarily urgent; the broken bot is now experimental while we work on fixing it. It doesn't block the CQ any more so we have time to figure out what to do.

I tried this patch, there's a #error that makes turning off GLX fail compile:

../../third_party/angle/src/libANGLE/Display.cpp:42:9: error: #error Unsupported OpenGL platform.
 #       error Unsupported OpenGL platform.
         ^
../../third_party/angle/src/libANGLE/Display.cpp:138:2: error: #error Unsupported OpenGL platform.
 #error Unsupported OpenGL platform.

Patch-set: 1