Fix a type error on 32-bit platforms.
FileStreamSeek was incorrectly typed to always take a 64-bit integer,
but fseeko takes off_t, which is 32 bits on 32 bit platforms.

This results in the following error:
error: implicit conversion loses integer precision:
'long long' to 'off_t' (aka 'long') [-Werror,-Wshorten-64-to-32]
  580 |     return fseeko(stream, offset, whence);
      |            ~~~~~~         ^~~~~~

Bug: chromium:425527533
Change-Id: I2fe2596accd33bf41db2dbed2df9a23c3fcd3871
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6918314
Commit-Queue: Shahbaz Youssefi <syoussefi@chromium.org>
Reviewed-by: Shahbaz Youssefi <syoussefi@chromium.org>
Auto-Submit: Matt Stark <msta@google.com>
Reviewed-by: Cody Northrop <cnorthrop@google.com>