Tests: Skip VerifyMutableRenderBufferKHR on Intel+Win
The test
EGLSingleBufferTest.VerifyMutableRenderBufferKHR/ES*_Vulkan_NoFixture is
failing on Intel+Windows and generating VVL errors.

ERR: vk_renderer.cpp:968 (rx::vk::(anonymous
namespace)::DebugUtilsMessenger): [
VUID-VkSwapchainCreateInfoKHR-presentMode-parameter ]
vkCreateSwapchainKHR(): pCreateInfo->presentMode
(VK_PRESENT_MODE_SHARED_DEMAND_REFRESH_KHR) requires the extensions
VK_KHR_shared_presentable_image.
The Vulkan spec states: presentMode must be a valid VkPresentModeKHR
value
(https://docs.vulkan.org/spec/latest/chapters/VK_KHR_surface/wsi.html#VUID-VkSwapchainCreateInfoKHR-presentMode-parameter)

..\..\src\tests\egl_tests\EGLSurfaceTest.cpp(2036): error: Value of:
IsEGLDisplayExtensionEnabled(mDisplay, "EGL_KHR_mutable_render_buffer")
  Actual: false
  Expected: true

It's not entirely clear where things are going wrong, but appears to be
something in the Intel+Windows driver. Skip the test for now to keep
win-exp-test green otherwise.

Bug: b/417459061
Test: EGLSingleBufferTest.VerifyMutableRenderBufferKHR
Change-Id: Iee848b46cddaf05d0cbb0c2d81d76d07dd0b9bba
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6548415
Auto-Submit: Tim Van Patten <timvp@google.com>
Reviewed-by: Amirali Abdolrashidi <abdolrashidi@google.com>
Commit-Queue: Amirali Abdolrashidi <abdolrashidi@google.com>