Update patch set 6
Patch Set 6:

It fails to compile on this bot:
https://luci-logdog.appspot.com/v/?s=chromium%2Fbb%2Fchromium.fyi%2FLibfuzzer_Upload_Linux_ASan%2F5147%2F%2B%2Frecipes%2Fsteps%2Fcompile%2F0%2Fstdout


FAILED: obj/third_party/angle/translator/emulated_builtin_functions_hlsl_autogen.o 
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/third_party/angle/translator/emulated_builtin_functions_hlsl_autogen.o.d -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_ENABLE_VULKAN -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DNO_TCMALLOC -DMEMORY_TOOL_REPLACES_ALLOCATOR -DMEMORY_SANITIZER_INITIAL_SIZE -DADDRESS_SANITIZER -DLEAK_SANITIZER -DDISABLE_NACL -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DFIELDTRIAL_TESTING_ENABLED -DCR_CLANG_REVISION=\"305735-1\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -DSANITIZER_COVERAGE -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGL_GLEXT_PROTOTYPES -DEGL_EGLEXT_PROTOTYPES -DANGLE_X64_CPU -DANGLE_TRANSLATOR_DISABLE_POOL_ALLOC -I../../third_party/angle/include -I../../third_party/angle/src -I../../third_party/angle/include -I../../third_party/angle/src/common/third_party/base -Igen/angle -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -B../../third_party/binutils/Linux_x64/Release/bin -pthread -fcolor-diagnostics -m64 -march=x86-64 -Wall -Werror -Wextra -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-covered-switch-default -Wno-unneeded-internal-declaration -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-address-of-packed-member -Wno-unused-lambda-capture -Wno-user-defined-warnings -O1 -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 --sysroot=../../build/linux/debian_jessie_amd64-sysroot -gline-tables-only -gcolumn-info -fno-omit-frame-pointer -fsanitize-coverage=trace-pc-guard -mllvm -sanitizer-coverage-prune-blocks=1 -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-blacklist=../../tools/memory/asan/blacklist.txt -fsanitize=leak -fvisibility=hidden -Xclang -load -Xclang ../../third_party/llvm-build/Release+Asserts/lib/libFindBadConstructs.so -Xclang -add-plugin -Xclang find-bad-constructs -Xclang -plugin-arg-find-bad-constructs -Xclang check-auto-raw-pointer -Xclang -plugin-arg-find-bad-constructs -Xclang check-ipc -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -std=gnu++11 -nostdinc++ -isystem../../buildtools/third_party/libc++/trunk/include -isystem../../buildtools/third_party/libc++abi/trunk/include -fno-rtti -fno-exceptions -fvisibility-inlines-hidden -c ../../third_party/angle/src/compiler/translator/emulated_builtin_functions_hlsl_autogen.cpp -o obj/third_party/angle/translator/emulated_builtin_functions_hlsl_autogen.o
../../third_party/angle/src/compiler/translator/emulated_builtin_functions_hlsl_autogen.cpp:19:51: error: constexpr variable 'g_hlslFunctions' must be initialized by a constant expression
constexpr std::pair<MiniFunctionId, const char *> g_hlslFunctions[] = {
                                                  ^                   ~
../../third_party/angle/src/compiler/translator/emulated_builtin_functions_hlsl_autogen.cpp:20:5: note: non-constexpr constructor 'pair<true, false>' cannot be used in a constant expression
    {{EOpMod, ParamType::Float1, ParamType::Float1},
    ^
../../buildtools/third_party/libc++/trunk/include/utility:422:5: note: declared here
    pair(_T1 const& __t1, _T2 const& __t2)
    ^
1 error generated.

Patch-set: 6
CC: Vitaly Buka <1001348@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>