Revert "CGL, MTL: pbuffer for IOSurface fails for some formats"
This reverts commit 5b84ad7973a3019b66848aabb2d2eef27c094545.

Reason for revert: Breaks the build on the bots (see below)

Example AutoRoll CL that has compilation pre-submit error: https://chromium-review.googlesource.com/c/chromium/src/+/3598558

Example bot results, showing compilation error: https://ci.chromium.org/ui/p/chromium/builders/try/ios-simulator/1143059/overview

Original change's description:
> CGL, MTL: pbuffer for IOSurface fails for some formats
>
> Some IOSurface SPI formats are compressed, and getting the
> element size for those returns values that are not consistent
> with the validation. Disable the validation
> until a better detection of such formats are known.
>
> A workaround exists for EAGL.
> Apply similar workaround for CGL and Metal.
>
> This hunk is in downtstream WebKit ANGLE and having it upstream would
> help merging back and forth.
>
> Bug: angleproject:7175
> Change-Id: Ic97afd3b952fed236e7b7e1e8511a1dde9008647
> Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3568380
> Reviewed-by: Geoff Lang <geofflang@chromium.org>
> Reviewed-by: Kenneth Russell <kbr@chromium.org>
> Commit-Queue: Kenneth Russell <kbr@chromium.org>

Bug: angleproject:7175
Change-Id: I0c18bdb800e39d6930455dbc86931681b6df20b1
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/3600148
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Ian Elliott <ianelliott@google.com>
Commit-Queue: Ian Elliott <ianelliott@google.com>
Auto-Submit: Ian Elliott <ianelliott@google.com>