Update patch set 2
Patch Set 2:

Are there instructions somewhere on what workflow I need to use? I'm not familiar with this coming from chromium.

For the record, now I tried

F:\src\angle>F:\src\angle>git rebase -i
'F:\src\angle' is not recognized as an internal or external command,
operable program or batch file.

F:\src\angle>git rebase -i master
Successfully rebased and updated refs/heads/fixd3d.

F:\src\angle>git cl upload
Using 50% similarity for rename/copy detection. Override with --similarity.
Loaded authentication cookies from c:/Users/jabdelmalek/.codereview_upload_cookies
Running presubmit upload checks ...

Presubmit checks passed.
 BUILD.gn | 10 ++++++++--
 1 file changed, 8 insertions(+), 2 deletions(-)
WARNING: This will upload 2 commits. Run the following command to see which commits will be uploaded:
git log origin/master..
You can also use `git squash-branch` to squash these into a singlecommit.
About to upload; enter to confirm.
Total 0 (delta 0), reused 0 (delta 0)
remote: Processing changes: refs: 1, done
To https://chromium.googlesource.com/angle/angle
 ! [remote rejected] HEAD -> refs/for/master (no new changes)
error: failed to push some refs to 'https://chromium.googlesource.com/angle/angle'
Command "git push origin HEAD:refs/for/master" failed.

F:\src\angle>git squash-branch
Traceback (most recent call last):
  File "f:\src\depot_tools\git_squash_branch.py", line 20, in <module>
    sys.exit(main(sys.argv[1:]))
  File "f:\src\depot_tools\git_squash_branch.py", line 17, in main
    squash_current_branch(opts.message)
  File "f:\src\depot_tools\git_common.py", line 611, in squash_current_branch
    log_msg += run('log', '--reverse', '--format=%H%n%B', '%s..HEAD' % merge_base)
  File "f:\src\depot_tools\git_common.py", line 543, in run
    return run_with_stderr(*cmd, **kwargs)[0]
  File "f:\src\depot_tools\git_common.py", line 588, in run_with_stderr
    raise subprocess2.CalledProcessError(retcode, cmd, os.getcwd(), ret, err)
subprocess2.CalledProcessError: Command f:\src\depot_tools\git.bat -c color.ui=never log --reverse --format=%H%n%B None..HEAD returned non-zero exit s
tatus 128 in F:\src\angle
fatal: ambiguous argument 'None..HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Patch-set: 2
Label: Code-Review=0