Revert "Roll vulkan-validation-layers. (2/2)"
This reverts commit 2feaa5e0ac6b779e13254c84b41de436f5d14765.

Reason for revert: Broke the Chrome Windows builders.

Build: https://build.chromium.org/p/chromium/builders/Win/builds/53432
Error: src\third_party\vulkan-validation-layers\src\include\vulkan\vk_layer.h(39): fatal error C1083: Cannot open include file: 'vk_layer_dispatch_table.h': No such file or directory

Original change's description:
> Roll vulkan-validation-layers. (2/2)
> 
> https://android.googlesource.com/platform/external/vulkan-validation-layers.git/+log/bcb80d06bbdc09..f47c534fee2f26f
> 
> This CL re-enables Vulkan with the new build files.
> 
> In particular, this roll contains a fix for a vs2017 signed/unsigned
> mismatch warning as error.
> 
> BUG=chromium:683729
> 
> Change-Id: Id38e10f97702cac5a51ee194c81972861f15db21
> Reviewed-on: https://chromium-review.googlesource.com/457278
> Commit-Queue: Jamie Madill <jmadill@chromium.org>
> Reviewed-by: Jamie Madill <jmadill@chromium.org>
> 

TBR=geofflang@chromium.org,jmadill@chromium.org,bungeman@chromium.org,cwallez@chromium.org
# Not skipping CQ checks because original CL landed > 1 day ago.
BUG=chromium:683729

Change-Id: Ic60f22496fc57904132d574a2fb2c1ca4d875b3e
Reviewed-on: https://chromium-review.googlesource.com/461999
Reviewed-by: Geoff Lang <geofflang@chromium.org>