Update patch set 2
Patch Set 2:

Welp, now it no longer builds in the build configs where UNREACHABLE() is noreturn:


FAILED: obj/third_party/angle/translator/ParseContext.o 
../../third_party/angle/src/compiler/translator/ParseContext.cpp:4999:17: error: fallthrough annotation in unreachable code [-Werror,-Wimplicit-fallthrough]
                ANGLE_FALLTHROUGH;
                ^

Patch-set: 2
Reviewer: Nico Weber <1001629@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>