Update patch set 14
Patch Set 14:

Hm, apparently on feature level 9_3 these formats become non-filterable. What should I do about this?

[----------] 4 tests from D3D11FormatTablesTest
[ RUN      ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_9_3
c:\users\kainino\src\chrome\src\third_party\angle\src\tests\gl_tests\d3d11formattablestest.cpp(88): error: Value of: textureInfo.filterable
  Actual: false
Expected: filterable
Which is: true
c:\users\kainino\src\chrome\src\third_party\angle\src\tests\gl_tests\d3d11formattablestest.cpp(88): error: Value of: textureInfo.filterable
  Actual: false
Expected: filterable
Which is: true
c:\users\kainino\src\chrome\src\third_party\angle\src\tests\gl_tests\d3d11formattablestest.cpp(88): error: Value of: textureInfo.filterable
  Actual: false
Expected: filterable
Which is: true
c:\users\kainino\src\chrome\src\third_party\angle\src\tests\gl_tests\d3d11formattablestest.cpp(88): error: Value of: textureInfo.filterable
  Actual: false
Expected: filterable
Which is: true
[  FAILED  ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_9_3, where GetParam() = ES2_D3D11_9_3 (22 ms)
[ RUN      ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_10_0
[       OK ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_10_0 (21 ms)
[ RUN      ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_10_1
[       OK ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_10_1 (22 ms)
[ RUN      ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_11_0
[       OK ] D3D11FormatTablesTest.TestFormatSupport/ES2_D3D11_11_0 (23 ms)

Patch-set: 14