Update patch set 21
Patch Set 21:

(1 comment)

This new test seems to be failing on Intel D3D11:

https://build.chromium.org/p/chromium.gpu.fyi/builders/Win10%20Release%20%28Intel%20HD%20630%29/builds/450

[ RUN      ] FramebufferTest_ES31.RenderingLimitToDefaultFBOSizeWithNoAttchments/ES3_1_D3D11
../../third_party/angle/src/tests/gl_tests/FramebufferTest.cpp(539): error:       Expected: static_cast<GLint>(passedCount)
      Which is: 1
To be equal to: 0
../../third_party/angle/src/tests/gl_tests/FramebufferTest.cpp(546): error:       Expected: static_cast<GLint>(passedCount)
      Which is: 1
To be equal to: 0
../../third_party/angle/src/tests/gl_tests/FramebufferTest.cpp(539): error:       Expected: static_cast<GLint>(passedCount)
      Which is: 1
To be equal to: 0
../../third_party/angle/src/tests/gl_tests/FramebufferTest.cpp(546): error:       Expected: static_cast<GLint>(passedCount)
      Which is: 1
To be equal to: 0
[  FAILED  ] FramebufferTest_ES31.RenderingLimitToDefaultFBOSizeWithNoAttchments/ES3_1_D3D11, where GetParam() = ES3_1_D3D11 (24 ms)

Patch-set: 21