Update the gn arg to avoid warning message in gn desc json file
After this change
https://chromium-review.googlesource.com/c/chromium/src/+/6547915,
using android32_ndk_api_level and android64_ndk_api_level gn args
will results in a warning message generated at the top of the
gn desc json file:

WARNING Build argument has no effect.
android32_ndk_api_level = 26
                          ^-
Did you mean "android_ndk_api_level"?

This causes the json.load() function in generate_android_bp.py failing
when parsing the json file

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Update roll_aosp.sh to use the android_ndk_apk_level to remove the
warning message.

Also update the gn arg from android32_ndk_apk_level and
android64_ndk_api_level to android_ndk_apk_level in other files.

Bug: b/418837345
Change-Id: I12fa48dcb5638b37a9965d0adb339a2dee018297
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6576736
Commit-Queue: Yuxin Hu <yuxinhu@google.com>
Reviewed-by: Cody Northrop <cnorthrop@google.com>
Auto-Submit: Yuxin Hu <yuxinhu@google.com>
Commit-Queue: Cody Northrop <cnorthrop@google.com>