[M140] Translator: Fix location validation for inout
  Without this validation, a shader using an inout variable can
write into a memory beyond the limit set by MaxDrawBuffers when
shader framebuffer fetch is enabled.

* Extended the location check in visitSymbol() to include InOut
  qualifiers (EvqFragmentInOut) as well (in ValidateOutputsTraverser).

* Moved RewritePixelLocalStorage() after ValidateOutputs() to avoid
  issues related to locations not being specified in the InOut nodes
  from the PLS implementation.

* Added a unit test to test that this case results in a compilation
  error: GLSLTest_ES3.CompileFSWithInoutLocBeyondMaxDrawBuffers

Bug: chromium:435139154
Change-Id: I44c729377a2e1d3126c2d279172217b2ab92b57b
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6806230
Reviewed-by: Shahbaz Youssefi <syoussefi@chromium.org>
Reviewed-by: Yuxin Hu <yuxinhu@google.com>
Commit-Queue: Shahbaz Youssefi <syoussefi@chromium.org>
(cherry picked from commit fc0e039788e8741ff8b4e8c58dbc1934c8148852)
Reviewed-on: https://chromium-review.googlesource.com/c/angle/angle/+/6830120
Reviewed-by: Charlie Lao <cclao@google.com>