Update patch set 3
Patch Set 3:

Think this is causing some test failures on the bots. The internal OOM is generating an error which is triggering the debug report callback extension, which is then making ANGLE call ERR() and the tests trap this and fail. See bot logs:

[ RUN      ] TextureRectangleTest.TexImage2D/ES2_OPENGL
../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(51): error: Failed
LogGLDebugMessage(145): 
	Source: OpenGL
	Type: Error
	ID: 0x0000
	Severity: High
	Message: Unknown internal debug message. The NVIDIA OpenGL driver has encountered
an out of memory error. This application might
behave inconsistently and fail.
../../third_party/angle/src/tests/test_utils/ANGLETest.cpp(51): error: Failed
LogGLDebugMessage(145): 
	Source: OpenGL
	Type: Error
	ID: 0x0505
	Severity: High
	Message: GL_OUT_OF_MEMORY error generated. Failed to allocate memory for texture.
[  FAILED  ] TextureRectangleTest.TexImage2D/ES2_OPENGL, where GetParam() = ES2_OPENGL (30 ms)

https://build.chromium.org/p/chromium.gpu.fyi/builders/Win10%20Release%20%28NVIDIA%20Quadro%20P400%29/builds/1538

Patch-set: 3
CC: Jamie Madill <1105324@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>