Update patch set 2
Patch Set 2:

I am not sure using a template method will help here, On mac it is complaining about not having float (*) (float) versions itself available in std::.

I don't yet know why these versions are not available as c++ standard itself has float and long double versions of these built-in math functions in addition to double versions. May be it is just a matter of using <cmath> instead of <math.h> but I don't have a mac setup to verify that.

There are also explicit float versions of these functions available like sinf, cosf, fabsf, etc but I did not use it earlier as overloaded version should ideally be available everywhere.

Will just check if these explicit versions work without any errors  on Windows and Linux (clang + gcc) and if it works then I can upload patches using explicit versions. From the compile error, looks like these versions are available on mac at least (error: no member named 'sin' in namespace 'std'; did you mean 'sinf')

Patch-set: 2